---
#- name: Set Description
#  shell: "lxc network set {{ oitem.name }} description '{{ oitem.description }}'"
#- name: set localhost
#  set_fact:
#    localhost: "{{ lookup('pipe', 'hostname') }}"
- name: debug local_hostname
  debug:
    var: 
      - lxd_networks_local_hostname
      - lxd_networks_local_ip
- name: Ajouter le vxlan
  include: vxlan.yml
  when: "{{ oitem.vxlan }}"
- name: debug route
  debug:
    var: route
