---
- name: Create VLAN network
  debug:
      var:  oitem
#     #- name: Set Description
#     #  shell: "lxc network set {{ oitem.name }} description '{{ oitem.description }}'"
#     #- name: set localhost
#     #  set_fact:
#     #    localhost: "{{ lookup('pipe', 'hostname') }}"
#     - name: debug local_hostname
#       debug:
#         var: 
#           - lxd_networks_local_hostname
#           - lxd_networks_local_ip
- name: Ajouter le vxlan
  include: vxlan.yml
  when: "{{ oitem.vxlan }}"
- name: Set vlan interface
  become: true
  command: "ip link add link {{ oitem.interface_phy }} name vlan-{{ oitem.vlan_id }} type vlan id {{ oitem.vlan_id }}"
  ignore_errors: true
- name: Set up vlan interface
  become: true
  command: "ip link set vlan-{{ oitem.vlan_id }} up"
- name: Flush ips of vlan interface
  become: true
  command: "ip a flush dev vlan-{{ oitem.vlan_id }}"
- name: Set external interface
  shell: "lxc network set {{ oitem.name }} bridge.external_interfaces vlan-{{ oitem.vlan_id  }}"
- name: Delete ipv4 
  shell: "lxc network unset {{ oitem.name }} ipv4.address"
- name: Delete ipv6 
  shell: "lxc network unset {{ oitem.name }} ipv6.address"
- name: Delete ipv4.nat 
  shell: "lxc network unset {{ oitem.name }} ipv4.nat"
- name: Delete ipv6.nat 
  shell: "lxc network unset {{ oitem.name }} ipv6.nat"
- name: debug route
  debug:
    var: route
